training_data = [
    [('Manila', 'NOUN'), ('is', 'VERB'), ('the', 'DET'), ('capital', 'NOUN'), ('of', 'NOUN'), ('Philippines', 'NOUN')],
    [('Cebu', 'NOUN'), ('attracts', 'VERB'), ('many', 'ADJ'), ('tourists', 'NOUN'), ('annually', 'ADV')],
    [('The', 'DET'), ('Filipino', 'ADJ'), ('cuisine', 'NOUN'), ('features', 'VERB'), ('tropical', 'ADJ'), ('fruits', 'NOUN')],
    [('Boracay', 'NOUN'), ('has', 'VERB'), ('beautiful', 'ADJ'), ('white', 'ADJ'), ('beaches', 'NOUN')],
    [('Tagalog', 'NOUN'), ('is', 'VERB'), ('an', 'DET'), ('official', 'ADJ'), ('language', 'NOUN')],
    [('President', 'NOUN'), ('Marcos', 'NOUN'), ('governs', 'VERB'), ('the', 'DET'), ('country', 'NOUN')],
    [('Jeepneys', 'NOUN'), ('provide', 'VERB'), ('unique', 'ADJ'), ('transportation', 'NOUN'), ('options', 'NOUN')],
    [('Manny', 'NOUN'), ('Pacquiao', 'NOUN'), ('represented', 'VERB'), ('Filipino', 'ADJ'), ('boxing', 'NOUN'), ('internationally', 'ADV')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('government', 'NOUN'), ('is', 'VERB'), ('working', 'VERB'), ('on', 'PREP'), ('improving', 'VERB'), ('infrastructure', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('islands', 'NOUN'), ('are', 'VERB'), ('known', 'VERB'), ('for', 'PREP'), ('their', 'DET'), ('scenic', 'ADJ'), ('beaches', 'NOUN')],
    [('Manila', 'NOUN'), ('hosts', 'VERB'), ('various', 'ADJ'), ('cultural', 'ADJ'), ('events', 'NOUN')],
    [('Filipino', 'ADJ'), ('festivals', 'NOUN'), ('celebrate', 'VERB'), ('the', 'DET'), ('country’s', 'NOUN'), ('rich', 'ADJ'), ('heritage', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('election', 'NOUN'), ('is', 'VERB'), ('held', 'VERB'), ('every', 'DET'), ('three', 'NUM'), ('years', 'NOUN')],
    [('Davao', 'NOUN'), ('is', 'VERB'), ('famous', 'ADJ'), ('for', 'PREP'), ('its', 'DET'), ('Durian', 'NOUN'), ('fruit', 'NOUN')],
    [('The', 'DET'), ('Philippines', 'NOUN'), ('is', 'VERB'), ('an', 'DET'), ('archipelago', 'NOUN'), ('consisting', 'VERB'), ('of', 'PREP'), ('over', 'PREP'), ('7,000', 'NUM'), ('islands', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('economy', 'NOUN'), ('relies', 'VERB'), ('heavily', 'ADV'), ('on', 'PREP'), ('remittances', 'NOUN')],
    [('Taal', 'NOUN'), ('volcano', 'NOUN'), ('is', 'VERB'), ('one', 'NUM'), ('of', 'PREP'), ('the', 'DET'), ('most', 'ADV'), ('active', 'ADJ'), ('volcanoes', 'NOUN'), ('in', 'PREP'), ('the', 'DET'), ('Philippines', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('sea', 'NOUN'), ('is', 'VERB'), ('home', 'NOUN'), ('to', 'PREP'), ('diverse', 'ADJ'), ('marine', 'ADJ'), ('life', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('economy', 'NOUN'), ('is', 'VERB'), ('growing', 'VERB'), ('due', 'PREP'), ('to', 'PREP'), ('remittances', 'NOUN'), ('from', 'PREP'), ('overseas', 'ADJ'), ('Filipinos', 'NOUN')],
    [('The', 'DET'), ('Philippines', 'NOUN'), ('has', 'VERB'), ('a', 'DET'), ('diverse', 'ADJ'), ('culture', 'NOUN'), ('influenced', 'VERB'), ('by', 'PREP'), ('various', 'ADJ'), ('ethnic', 'ADJ'), ('groups', 'NOUN')],
    [('The', 'DET'), ('Philippine', 'ADJ'), ('president', 'NOUN'), ('visits', 'VERB'), ('different', 'ADJ'), ('regions', 'NOUN'), ('to', 'PREP'), ('address', 'VERB'), ('local', 'ADJ'), ('concerns', 'NOUN')],
    [('Palawan', 'NOUN'), ('is', 'VERB'), ('known', 'VERB'), ('for', 'PREP'), ('its', 'DET'), ('clear', 'ADJ'), ('waters', 'NOUN')],
    [('The', 'DET'), ('Philippines', 'NOUN'), ('has', 'VERB'), ('a', 'DET'), ('growing', 'ADJ'), ('tourism', 'NOUN'), ('industry', 'NOUN')],
    [('The', 'DET'), ('Banaue', 'NOUN'), ('Rice', 'NOUN'), ('Terraces', 'NOUN'), ('are', 'VERB'), ('a', 'DET'), ('UNESCO', 'NOUN'), ('World', 'NOUN'), ('Heritage', 'NOUN'), ('site', 'NOUN')],
    [('The', 'DET'), ('Philippines', 'NOUN'), ('celebrates', 'VERB'), ('Independence', 'NOUN'), ('Day', 'NOUN'), ('on', 'PREP'), ('June', 'NOUN'), ('12th', 'NUM')]
]